'use client'
import {useEffect,useMemo,useState} from 'react'
import {useParams,useRouter} from 'next/navigation'
import Link from 'next/link'
import {supabase} from '../../../../lib/supabase'
import '../../admin.css'
import '../students.css'
import './profile.css'

const emptyFee={fee_month:'',amount:'',paid_amount:'',payment_date:'',status:'due',note:''}
const emptyResult={exam_name:'',subject:'',max_marks:'100',marks:'',grade:'',remarks:'',exam_date:''}
const emptyAttendance={attendance_date:'',status:'present',note:''}

export default function StudentProfilePage(){
 const {id}=useParams(); const router=useRouter(); const sid=String(id)
 const [student,setStudent]=useState<any>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[tab,setTab]=useState('profile')
 const [form,setForm]=useState<any>({}),[fees,setFees]=useState<any[]>([]),[results,setResults]=useState<any[]>([]),[attendance,setAttendance]=useState<any[]>([])
 const [fee,setFee]=useState(emptyFee),[result,setResult]=useState(emptyResult),[att,setAtt]=useState(emptyAttendance)
 useEffect(()=>{load()},[sid])
 async function load(){setLoading(true);const {data:a}=await supabase.auth.getSession();if(!a.session){router.replace('/admin');return}const {data:s,error}=await supabase.from('student_profiles').select('*').eq('id',sid).eq('status','active').single();if(error||!s){setMessage(error?.message||'Approved student not found.');setLoading(false);return}setStudent(s);setForm({...s});const [f,r,at]=await Promise.all([supabase.from('student_fees').select('*').eq('student_profile_id',sid).order('id',{ascending:false}),supabase.from('student_results').select('*').eq('student_profile_id',sid).order('exam_date',{ascending:false}),supabase.from('student_attendance').select('*').eq('student_profile_id',sid).order('attendance_date',{ascending:false})]);setFees(f.data||[]);setResults(r.data||[]);setAttendance(at.data||[]);setLoading(false)}
 const totals=useMemo(()=>({fee:fees.reduce((n,x)=>n+Number(x.amount||0),0),paid:fees.reduce((n,x)=>n+Number(x.paid_amount||0),0),due:fees.reduce((n,x)=>n+Number(x.due_amount||0),0),present:attendance.filter(x=>x.status==='present').length}),[fees,attendance])
 async function saveProfile(){setSaving(true);const p={student_name:form.student_name||'',student_id:form.student_id||'',dob:form.dob||null,class_name:form.class_name||'',roll_number:form.roll_number||'',admission_date:form.admission_date||null,father_name:form.father_name||'',mother_name:form.mother_name||'',phone:form.phone||'',email:form.email||'',address:form.address||'',student_photo_url:form.student_photo_url||null,updated_at:new Date().toISOString()};const {error}=await supabase.from('student_profiles').update(p).eq('id',sid);if(!error){await supabase.from('admissions').update({student_name:p.student_name,dob:p.dob,class_applied:p.class_name,father_name:p.father_name,mother_name:p.mother_name,phone:p.phone,email:p.email,address:p.address,student_photo_url:p.student_photo_url}).eq('id',student.admission_id);setStudent({...student,...p});setMessage('Student details updated ✓')}else setMessage(error.message);setSaving(false)}
 async function addFee(){const amount=Number(fee.amount||0),paid=Number(fee.paid_amount||0);if(!fee.fee_month)return;const {error}=await supabase.from('student_fees').insert({student_profile_id:sid,fee_month:fee.fee_month,amount,paid_amount:paid,due_amount:Math.max(0,amount-paid),payment_date:fee.payment_date||null,status:fee.status,note:fee.note||null});setMessage(error?.message||'Payment entry saved ✓');if(!error){setFee(emptyFee);load()}}
 async function addResult(){if(!result.exam_name||!result.subject)return;const {error}=await supabase.from('student_results').insert({student_profile_id:sid,exam_name:result.exam_name,subject:result.subject,max_marks:Number(result.max_marks||0),marks:Number(result.marks||0),grade:result.grade||null,remarks:result.remarks||null,exam_date:result.exam_date||null});setMessage(error?.message||'Result saved ✓');if(!error){setResult(emptyResult);load()}}
 async function addAttendance(){if(!att.attendance_date)return;const {error}=await supabase.from('student_attendance').insert({student_profile_id:sid,attendance_date:att.attendance_date,status:att.status,note:att.note||null});setMessage(error?.message||'Attendance saved ✓');if(!error){setAtt(emptyAttendance);load()}}
 async function remove(table:string,row:number){if(!confirm('Delete this record?'))return;const {error}=await supabase.from(table).delete().eq('id',row);setMessage(error?.message||'Deleted ✓');if(!error)load()}
 const print=()=>setTimeout(()=>window.print(),50)
 if(loading)return <div className="studentsPage"><div className="studentEmpty">Loading student profile…</div></div>
 if(!student)return <div className="studentsPage"><div className="studentEmpty"><strong>Student not found</strong><span>{message}</span><Link href="/admin/students">← Approved Students</Link></div></div>
 return <div className="studentProfilePage"><header className="profilePageTop"><div><span className="adminKicker">APPROVED STUDENT</span><h1>Student Profile</h1><p>Complete profile, fees, results, attendance and ID card.</p></div><div className="profileTopActions"><button onClick={print}>🖨 Print / Save PDF</button><Link href="/admin/students">← Approved Students</Link><Link href="/admin">⌂ Dashboard</Link></div></header>{message&&<div className="profileMessage">{message}</div>}<section className="profileSummary"><div className="profilePhoto">{student.student_photo_url?<img src={student.student_photo_url} alt=""/>:<span>{(student.student_name||'S').slice(0,1)}</span>}</div><div><span className="activePill">ACTIVE • ADMISSION APPROVED</span><h2>{student.student_name}</h2><div className="profileIdentifiers"><span><b>Student ID</b>{student.student_id||'—'}</span><span><b>Class</b>{student.class_name||'—'}</span><span><b>Roll No.</b>{student.roll_number||'—'}</span><span><b>Admission Date</b>{student.admission_date||'—'}</span></div></div></section><nav className="profileNav"><button className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}>👤 Profile & Edit</button><button className={tab==='fees'?'active':''} onClick={()=>setTab('fees')}>₹ Fees & Payments</button><button className={tab==='results'?'active':''} onClick={()=>setTab('results')}>📊 Results & Marksheet</button><button className={tab==='attendance'?'active':''} onClick={()=>setTab('attendance')}>📅 Attendance</button><button className={tab==='idcard'?'active':''} onClick={()=>setTab('idcard')}>🪪 ID Card</button></nav>
 {tab==='profile'&&<section className="profileSection"><div className="profileSectionHead"><div><span>PERSONAL RECORD</span><h3>Student Details</h3></div><button onClick={saveProfile} disabled={saving}>{saving?'Saving…':'Save All Changes'}</button></div><div className="detailEditGrid"><label>Student Name<input value={form.student_name||''} onChange={e=>setForm({...form,student_name:e.target.value})}/></label><label>Student ID<input value={form.student_id||''} onChange={e=>setForm({...form,student_id:e.target.value})}/></label><label>Date of Birth<input type="date" value={form.dob||''} onChange={e=>setForm({...form,dob:e.target.value})}/></label><label>Class<input value={form.class_name||''} onChange={e=>setForm({...form,class_name:e.target.value})}/></label><label>Roll Number<input value={form.roll_number||''} onChange={e=>setForm({...form,roll_number:e.target.value})}/></label><label>Admission Date<input type="date" value={form.admission_date||''} onChange={e=>setForm({...form,admission_date:e.target.value})}/></label><label>Father's Name<input value={form.father_name||''} onChange={e=>setForm({...form,father_name:e.target.value})}/></label><label>Mother's Name<input value={form.mother_name||''} onChange={e=>setForm({...form,mother_name:e.target.value})}/></label><label>Mobile Number<input value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Email Address<input value={form.email||''} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="wideField">Full Address<textarea value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})}/></label></div><div className="quickStats"><div><b>₹{totals.fee.toLocaleString('en-IN')}</b><span>Total Fees</span></div><div><b>₹{totals.paid.toLocaleString('en-IN')}</b><span>Total Paid</span></div><div><b>₹{totals.due.toLocaleString('en-IN')}</b><span>Total Due</span></div><div><b>{attendance.length?Math.round(totals.present/attendance.length*100):0}%</b><span>Attendance</span></div></div></section>}
 {tab==='fees'&&<section className="profileSection"><div className="profileSectionHead"><div><span>FEE MANAGEMENT</span><h3>Payments & Fee Ledger</h3></div><div className="feeSummary"><span>Total ₹{totals.fee}</span><span>Paid ₹{totals.paid}</span><b>Due ₹{totals.due}</b></div></div><div className="entryForm"><input placeholder="Month / Term" value={fee.fee_month} onChange={e=>setFee({...fee,fee_month:e.target.value})}/><input type="number" min="0" placeholder="Total fee" value={fee.amount} onChange={e=>setFee({...fee,amount:e.target.value})}/><input type="number" min="0" placeholder="Payment received" value={fee.paid_amount} onChange={e=>setFee({...fee,paid_amount:e.target.value})}/><input type="date" value={fee.payment_date} onChange={e=>setFee({...fee,payment_date:e.target.value})}/><select value={fee.status} onChange={e=>setFee({...fee,status:e.target.value})}><option value="paid">Paid</option><option value="partial">Partial</option><option value="due">Due</option></select><input placeholder="Payment note" value={fee.note} onChange={e=>setFee({...fee,note:e.target.value})}/><button onClick={addFee}>+ Add Payment</button></div><div className="recordRows">{fees.map(x=><div key={x.id}><span><b>{x.fee_month}</b> Total ₹{x.amount} · Paid ₹{x.paid_amount} · Due ₹{x.due_amount}</span><b className={x.status}>{x.status}</b><button onClick={()=>remove('student_fees',x.id)}>Delete</button></div>)}{!fees.length&&<p>No fee/payment entries yet.</p>}</div></section>}
 {tab==='results'&&<section className="profileSection"><div className="profileSectionHead"><div><span>ACADEMIC MANAGEMENT</span><h3>Results & Marksheet</h3></div><button onClick={print}>🖨 Print / Save PDF</button></div><div className="entryForm"><input placeholder="Exam name" value={result.exam_name} onChange={e=>setResult({...result,exam_name:e.target.value})}/><input placeholder="Subject" value={result.subject} onChange={e=>setResult({...result,subject:e.target.value})}/><input type="number" min="0" placeholder="Max marks" value={result.max_marks} onChange={e=>setResult({...result,max_marks:e.target.value})}/><input type="number" min="0" placeholder="Marks obtained" value={result.marks} onChange={e=>setResult({...result,marks:e.target.value})}/><input placeholder="Grade" value={result.grade} onChange={e=>setResult({...result,grade:e.target.value})}/><input type="date" value={result.exam_date} onChange={e=>setResult({...result,exam_date:e.target.value})}/><input placeholder="Remarks" value={result.remarks} onChange={e=>setResult({...result,remarks:e.target.value})}/><button onClick={addResult}>+ Add Result</button></div><div className="recordRows">{results.map(x=><div key={x.id}><span><b>{x.exam_name}</b> · {x.subject} · {x.marks}/{x.max_marks} · Grade {x.grade||'—'}</span><button onClick={()=>remove('student_results',x.id)}>Delete</button></div>)}{!results.length&&<p>No results entered yet.</p>}</div><div className="marksheetPreview"><h2>NEW SUNRISE PUBLIC SCHOOL</h2><p>Kallyangaon, Bihar – 854317</p><h3>ACADEMIC MARKSHEET</h3><p><b>Student:</b> {student.student_name} &nbsp; <b>ID:</b> {student.student_id} &nbsp; <b>Class:</b> {student.class_name}</p><table><thead><tr><th>Exam</th><th>Subject</th><th>Max</th><th>Marks</th><th>Grade</th></tr></thead><tbody>{results.map(x=><tr key={x.id}><td>{x.exam_name}</td><td>{x.subject}</td><td>{x.max_marks}</td><td>{x.marks}</td><td>{x.grade||'—'}</td></tr>)}</tbody></table><div className="signatureLine"><span>Class Teacher</span><span>Principal</span><span>School Seal</span></div></div></section>}
 {tab==='attendance'&&<section className="profileSection"><div className="profileSectionHead"><div><span>DAILY RECORD</span><h3>Attendance Management</h3></div><b>{attendance.length?Math.round(totals.present/attendance.length*100):0}% Attendance</b></div><div className="entryForm"><input type="date" value={att.attendance_date} onChange={e=>setAtt({...att,attendance_date:e.target.value})}/><select value={att.status} onChange={e=>setAtt({...att,status:e.target.value})}><option value="present">Present</option><option value="absent">Absent</option><option value="leave">Leave</option></select><input placeholder="Note" value={att.note} onChange={e=>setAtt({...att,note:e.target.value})}/><button onClick={addAttendance}>+ Add Attendance</button></div><div className="recordRows">{attendance.map(x=><div key={x.id}><span><b>{x.attendance_date}</b> · {x.note||'No note'}</span><b className={x.status}>{x.status}</b><button onClick={()=>remove('student_attendance',x.id)}>Delete</button></div>)}{!attendance.length&&<p>No attendance records yet.</p>}</div></section>}
 {tab==='idcard'&&<section className="profileSection idCardSection"><div className="profileSectionHead"><div><span>IDENTIFICATION</span><h3>Student ID Card</h3></div><button onClick={print}>🖨 Print ID Card</button></div><div className="idCard"><div className="idCardTop"><div className="idLogo">NS</div><div><strong>NEW SUNRISE PUBLIC SCHOOL</strong><span>STUDENT IDENTITY CARD</span></div></div><div className="idCardBody"><div className="idPhoto">{student.student_photo_url?<img src={student.student_photo_url} alt=""/>:<span>{(student.student_name||'S').slice(0,1)}</span>}</div><div className="idInfo"><h4>{student.student_name}</h4><p><b>Student ID:</b> {student.student_id}</p><p><b>Class:</b> {student.class_name}</p><p><b>Roll:</b> {student.roll_number||'—'}</p><p><b>DOB:</b> {student.dob||'—'}</p><p><b>Father:</b> {student.father_name||'—'}</p><p><b>Phone:</b> {student.phone||'—'}</p></div></div><div className="idCardBottom">Kallyangaon, Bihar – 854317 <span>AUTHORIZED</span></div></div></section>}
 </div>
}
