'use client'
import './student.css'
import {useState} from 'react'
import Link from 'next/link'
import {supabase} from '../../lib/supabase'

const fn='https://stypnhzdnsgmyngqkpmz.supabase.co/functions/v1/student-portal-v3'
const emailFor=(id:string)=>`${id.toLowerCase().replace(/[^a-z0-9]/g,'')}@students.newsunrise.local`

export default function StudentPortal(){
 const [app,setApp]=useState(''),[status,setStatus]=useState<any>(null),[statusMsg,setStatusMsg]=useState(''),[id,setId]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false)
 async function checkStatus(e:any){e.preventDefault();setBusy(true);setStatus(null);setStatusMsg('');try{const r=await fetch(fn,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'status',application_number:app.trim()})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to check status.');setStatus(d)}catch(e:any){setStatusMsg(e.message)}finally{setBusy(false)}}
 async function login(e:any){e.preventDefault();setBusy(true);setStatusMsg('');try{const prep=await fetch(fn,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'ensure_login',student_id:id.trim(),password})});const pd=await prep.json();if(!prep.ok)throw new Error(pd.error||'Student account is not ready.');const {error}=await supabase.auth.signInWithPassword({email:pd.email||emailFor(id.trim()),password});if(error)throw error;window.location.href='/student/profile'}catch(e:any){setStatusMsg(e.message||'Login failed.')}finally{setBusy(false)}}
 return <main className="studentPortal"><div className="studentTop"><Link href="/" className="back">← New Sunrise Public School</Link><span>STUDENT PORTAL</span></div><section className="studentHero"><div><div className="portalKicker">NEW SUNRISE • STUDENT SERVICES</div><h1>Your school account, in one place.</h1><p>Check your admission application or securely access your student profile, fees, results and attendance.</p></div><div className="portalBadge">NS<br/><small>STUDENT</small></div></section><section className="portalGrid"><div className="portalCard"><div className="cardIcon">01</div><h2>Check Application Status</h2><p>Enter the application number you received after submitting your admission form.</p><form onSubmit={checkStatus}><label>Application Number<input value={app} onChange={e=>setApp(e.target.value)} placeholder="e.g. NSPS-APP-12345678" required/></label><button disabled={busy}>{busy?'Checking…':'Check Status →'}</button></form>{status&&<div className={`statusResult ${status.status}`}><strong>{status.status==='verified'?'Approved':status.status==='rejected'?'Rejected':'Under Review'}</strong><span>Application: {status.application_number}</span>{status.student_id&&<span>Student ID: <b>{status.student_id}</b></span>}</div>}</div><div className="portalCard featured"><div className="cardIcon">02</div><h2>Student Login</h2><p>Use your Student ID as the username. On your first login, your default password is your DOB in <b>DDMMYYYY</b> format.</p><form onSubmit={login}><label>Student ID<input value={id} onChange={e=>setId(e.target.value.toUpperCase())} placeholder="NSPSABC03082002" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Your password" required/></label><button disabled={busy}>{busy?'Signing in…':'Access My Profile →'}</button></form><small className="securityNote">First login: you will be asked to create your permanent password.</small></div></section>{statusMsg&&<div className="portalError">{statusMsg}</div>}<footer className="portalFooter"><Link href="/admission">Apply for Admission</Link><Link href="/">Back to School Website</Link></footer></main>
}
