'use client'
import {useEffect,useState} from 'react'
import {supabase} from '../../lib/supabase'
import Link from 'next/link'

export default function Admin(){
 const [session,setSession]=useState<any>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[tab,setTab]=useState('settings'),[msg,setMsg]=useState('')
 const [settings,setSettings]=useState<any[]>([]),[notices,setNotices]=useState<any[]>([]),[teachers,setTeachers]=useState<any[]>([]),[gallery,setGallery]=useState<any[]>([]),[admissions,setAdmissions]=useState<any[]>([])
 const [form,setForm]=useState<any>({title:'',body:'',important:false,name:'',subject:'',qualification:'',image_url:'',gallery_title:'',gallery_image:''})
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>data.subscription.unsubscribe()},[])
 async function load(){const [s,n,t,g,a]=await Promise.all([supabase.from('site_settings').select('*').order('key'),supabase.from('notices').select('*').order('id',{ascending:false}),supabase.from('teachers').select('*').order('id',{ascending:false}),supabase.from('gallery').select('*').order('id',{ascending:false}),supabase.from('admissions').select('*').order('id',{ascending:false})]);setSettings(s.data||[]);setNotices(n.data||[]);setTeachers(t.data||[]);setGallery(g.data||[]);setAdmissions(a.data||[])}
 useEffect(()=>{if(session)load()},[session])
 async function login(e:any){e.preventDefault();const {error}=await supabase.auth.signInWithPassword({email,password});setMsg(error?error.message:'Logged in');}
 async function saveSetting(key:string,value:string){await supabase.from('site_settings').update({value,updated_at:new Date().toISOString()}).eq('key',key);setMsg('Saved');}
 async function addNotice(){if(!form.title||!form.body)return;await supabase.from('notices').insert({title:form.title,body:form.body,important:form.important});setForm({...form,title:'',body:''});load()}
 async function addTeacher(){await supabase.from('teachers').insert({name:form.name,subject:form.subject,qualification:form.qualification,image_url:form.image_url});setForm({...form,name:'',subject:'',qualification:'',image_url:''});load()}
 async function addGallery(){await supabase.from('gallery').insert({title:form.gallery_title,image_url:form.gallery_image});setForm({...form,gallery_title:'',gallery_image:''});load()}
 async function remove(table:string,id:number){await supabase.from(table).delete().eq('id',id);load()}
 if(!session)return <div className="adminLogin"><div className="loginCard"><div className="brandmark">NS</div><h1>School Admin</h1><p>Sign in to manage website content, images, notices and admissions.</p><form onSubmit={login}><input type="email" placeholder="Admin email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><button>Sign in</button></form>{msg&&<small>{msg}</small>}<Link href="/">← Back to website</Link></div></div>
 return <div className="adminShell"><aside><div className="adminBrand"><div className="brandmark">NS</div><b>New Sunrise<br/>Admin</b></div>{['settings','notices','teachers','gallery','admissions'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x==='settings'?'⚙️ Site & Images':x==='notices'?'📢 Notices':x==='teachers'?'👩‍🏫 Faculty':x==='gallery'?'🖼️ Gallery':'📝 Admissions'}</button>)}<Link href="/">↗ View website</Link><button onClick={()=>supabase.auth.signOut()}>Logout</button></aside><section className="adminMain"><div className="adminTop"><div><small>CONTENT MANAGEMENT</small><h1>{tab==='settings'?'Site & Images':tab}</h1></div><span>Admin</span></div>
 {tab==='settings'&&<div className="adminGrid">{settings.map(s=><div className="settingCard" key={s.key}><label>{s.key.replaceAll('_',' ')}</label><input defaultValue={s.value} onBlur={e=>saveSetting(s.key,e.target.value)}/><small>Changes are saved to the live website.</small></div>)}</div>}
 {tab==='notices'&&<div><div className="adminForm"><input placeholder="Notice title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea placeholder="Notice details" value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/><label><input type="checkbox" checked={form.important} onChange={e=>setForm({...form,important:e.target.checked})}/> Important</label><button onClick={addNotice}>Publish Notice</button></div><div className="adminList">{notices.map(n=><div className="row" key={n.id}><div><b>{n.title}</b><p>{n.body}</p></div><button onClick={()=>remove('notices',n.id)}>Delete</button></div>)}</div></div>}
 {tab==='teachers'&&<div><div className="adminForm"><input placeholder="Teacher name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Subject" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/><input placeholder="Qualification" value={form.qualification} onChange={e=>setForm({...form,qualification:e.target.value})}/><input placeholder="Photo URL" value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/><button onClick={addTeacher}>Add Faculty</button></div><div className="adminList">{teachers.map(t=><div className="row" key={t.id}><div className="mini"><img src={t.image_url}/><span><b>{t.name}</b><small>{t.subject} • {t.qualification}</small></span></div><button onClick={()=>remove('teachers',t.id)}>Delete</button></div>)}</div></div>}
 {tab==='gallery'&&<div><div className="adminForm"><input placeholder="Image title" value={form.gallery_title} onChange={e=>setForm({...form,gallery_title:e.target.value})}/><input placeholder="Image URL (paste your hosted image URL)" value={form.gallery_image} onChange={e=>setForm({...form,gallery_image:e.target.value})}/><button onClick={addGallery}>Add Image</button></div><div className="adminGallery">{gallery.map(g=><div key={g.id}><img src={g.image_url}/><b>{g.title}</b><button onClick={()=>remove('gallery',g.id)}>Delete</button></div>)}</div></div>}
 {tab==='admissions'&&<div className="adminList">{admissions.map(a=><div className="row" key={a.id}><div><b>{a.student_name} — Class {a.class_applied}</b><p>Father: {a.father_name} • Phone: {a.phone}<br/>{a.address}</p></div><button onClick={()=>remove('admissions',a.id)}>Delete</button></div>)}</div>}
 </section></div>
}
