'use client'
import './admin.css'
import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../../lib/supabase'
import Link from 'next/link'

type Tab='overview'|'settings'|'notices'|'teachers'|'gallery'|'admissions'
const tabs: {id:Tab;label:string;icon:string}[]=[
 {id:'overview',label:'Dashboard',icon:'⌂'}, {id:'settings',label:'Site & Images',icon:'▣'},
 {id:'notices',label:'Notices',icon:'!'},{id:'teachers',label:'Faculty',icon:'◉'},
 {id:'gallery',label:'Gallery',icon:'▧'},{id:'admissions',label:'Admissions',icon:'✎'}
]

export default function Admin(){
 const [session,setSession]=useState<any>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[tab,setTab]=useState<Tab>('overview'),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 const [settings,setSettings]=useState<Record<string,string>>({}),[notices,setNotices]=useState<any[]>([]),[teachers,setTeachers]=useState<any[]>([]),[gallery,setGallery]=useState<any[]>([]),[admissions,setAdmissions]=useState<any[]>([])
 const [notice,setNotice]=useState({title:'',body:'',important:false}),[teacher,setTeacher]=useState({name:'',subject:'',qualification:'',image_url:''}),[photo,setPhoto]=useState({title:'',image_url:''})
 const [editingTeacher,setEditingTeacher]=useState<number|null>(null),[editingNotice,setEditingNotice]=useState<number|null>(null)
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[])
 const load=async()=>{setBusy(true);const [s,n,t,g,a]=await Promise.all([supabase.from('site_settings').select('key,value').order('key'),supabase.from('notices').select('*').order('published_on',{ascending:false}),supabase.from('teachers').select('*').order('id',{ascending:false}),supabase.from('gallery').select('*').order('id',{ascending:false}),supabase.from('admissions').select('*').order('id',{ascending:false})]);const m:any={};(s.data||[]).forEach((x:any)=>m[x.key]=x.value);setSettings(m);setNotices(n.data||[]);setTeachers(t.data||[]);setGallery(g.data||[]);setAdmissions(a.data||[]);setBusy(false)}
 useEffect(()=>{if(session)load()},[session])
 async function login(e:any){e.preventDefault();setBusy(true);const {error}=await supabase.auth.signInWithPassword({email,password});setMsg(error?error.message:'Signed in');setBusy(false)}
 async function saveSetting(key:string,value:string){setSettings(x=>({...x,[key]:value}));const {error}=await supabase.from('site_settings').upsert({key,value,updated_at:new Date().toISOString()});setMsg(error?error.message:'Saved ✓')}
 async function saveNotice(){if(!notice.title.trim()||!notice.body.trim())return;const payload={title:notice.title.trim(),body:notice.body.trim(),important:notice.important};const q=editingNotice?supabase.from('notices').update(payload).eq('id',editingNotice):supabase.from('notices').insert(payload);const {error}=await q;setMsg(error?error.message:'Notice saved ✓');setNotice({title:'',body:'',important:false});setEditingNotice(null);load()}
 async function saveTeacher(){if(!teacher.name.trim())return;const q=editingTeacher?supabase.from('teachers').update(teacher).eq('id',editingTeacher):supabase.from('teachers').insert(teacher);const {error}=await q;setMsg(error?error.message:'Faculty saved ✓');setTeacher({name:'',subject:'',qualification:'',image_url:''});setEditingTeacher(null);load()}
 async function savePhoto(){if(!photo.image_url.trim())return;const {error}=await supabase.from('gallery').insert(photo);setMsg(error?error.message:'Image added ✓');setPhoto({title:'',image_url:''});load()}
 async function remove(table:string,id:number){if(!confirm('Delete this item?'))return;const {error}=await supabase.from(table).delete().eq('id',id);setMsg(error?error.message:'Deleted ✓');load()}
 const stats=useMemo(()=>[{label:'Notices',value:notices.length},{label:'Faculty',value:teachers.length},{label:'Gallery',value:gallery.length},{label:'Admissions',value:admissions.length}],[notices,teachers,gallery,admissions])
 if(!session)return <div className="adminLogin"><div className="loginCard"><div className="brandmark">NS</div><span className="adminKicker">NEW SUNRISE PUBLIC SCHOOL</span><h1>Admin Portal</h1><p>Manage your school website, photos, faculty, notices and admission enquiries from one place.</p><form onSubmit={login}><label>Email<input type="email" placeholder="Admin email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button disabled={busy}>{busy?'Signing in…':'Sign in securely'}</button></form>{msg&&<div className="error">{msg}</div>}<Link href="/">← Back to website</Link></div></div>
 return <div className="adminShell"><aside><div className="adminBrand"><div className="brandmark">NS</div><div><b>New Sunrise</b><small>School Admin</small></div></div><div className="sideLabel">MANAGE</div>{tabs.map(x=><button className={tab===x.id?'active':''} onClick={()=>setTab(x.id)} key={x.id}><i>{x.icon}</i>{x.label}</button>)}<div className="sideBottom"><Link href="/">↗ View live website</Link><button onClick={()=>supabase.auth.signOut()}>⇥ Logout</button></div></aside><section className="adminMain"><header className="adminTop"><div><small>CONTENT MANAGEMENT</small><h1>{tabs.find(x=>x.id===tab)?.label}</h1></div><div className="topActions">{busy&&<span>Saving…</span>}<span className="adminUser">● {session.user?.email}</span></div></header>{msg&&<div className="toast">{msg}</div>}
 {tab==='overview'&&<><div className="welcome"><div><span className="adminKicker">WELCOME BACK</span><h2>Keep your school website fresh.</h2><p>Update images, publish notices and review new admission enquiries.</p></div><Link href="/" className="viewBtn">View Website →</Link></div><div className="statGrid">{stats.map(s=><div className="stat" key={s.label}><strong>{s.value}</strong><span>{s.label}</span></div>)}</div><div className="twoCol"><div className="panel"><div className="panelHead"><h3>Recent Notices</h3><button onClick={()=>setTab('notices')}>Manage</button></div>{notices.slice(0,4).map(n=><div className="compactRow" key={n.id}><span>{n.important?'!':'•'}</span><div><b>{n.title}</b><small>{n.body}</small></div></div>)}</div><div className="panel"><div className="panelHead"><h3>Latest Admissions</h3><button onClick={()=>setTab('admissions')}>View all</button></div>{admissions.slice(0,4).map(a=><div className="compactRow" key={a.id}><span>✎</span><div><b>{a.student_name}</b><small>Class {a.class_applied} • {a.phone}</small></div></div>)}</div></div></>}
 {tab==='settings'&&<div><div className="panel intro"><h3>Website content & images</h3><p>Every field below is connected to Supabase. Replace an image URL with your own hosted image and it will appear on the live site.</p></div><div className="settingsGrid">{Object.entries(settings).map(([key,value])=><div className="settingCard" key={key}><label>{key.replaceAll('_',' ')}</label><input value={value} onChange={e=>setSettings(x=>({...x,[key]:e.target.value}))}/><button onClick={()=>saveSetting(key,value)}>Save</button>{key.includes('image')||key.includes('logo')?<img className="settingPreview" src={value||'/placeholder.svg'} alt="Preview"/>:null}</div>)}</div></div>}
 {tab==='notices'&&<div><div className="panel formPanel"><h3>{editingNotice?'Edit notice':'Publish a new notice'}</h3><div className="formGrid"><input placeholder="Notice title" value={notice.title} onChange={e=>setNotice({...notice,title:e.target.value})}/><label className="check"><input type="checkbox" checked={notice.important} onChange={e=>setNotice({...notice,important:e.target.checked})}/> Mark as important</label></div><textarea placeholder="Write notice details…" value={notice.body} onChange={e=>setNotice({...notice,body:e.target.value})}/><div><button className="saveBtn" onClick={saveNotice}>{editingNotice?'Update Notice':'Publish Notice'}</button>{editingNotice&&<button className="cancelBtn" onClick={()=>{setEditingNotice(null);setNotice({title:'',body:'',important:false})}}>Cancel</button>}</div></div><div className="panel"><h3>Published notices</h3>{notices.map(n=><div className="manageRow" key={n.id}><div><b>{n.title}</b><p>{n.body}</p>{n.important&&<em>IMPORTANT</em>}</div><div className="rowBtns"><button onClick={()=>{setEditingNotice(n.id);setNotice({title:n.title,body:n.body,important:!!n.important})}}>Edit</button><button className="danger" onClick={()=>remove('notices',n.id)}>Delete</button></div></div>)}</div></div>}
 {tab==='teachers'&&<div><div className="panel formPanel"><h3>{editingTeacher?'Edit faculty':'Add faculty member'}</h3><div className="formGrid four"><input placeholder="Teacher name" value={teacher.name} onChange={e=>setTeacher({...teacher,name:e.target.value})}/><input placeholder="Subject" value={teacher.subject} onChange={e=>setTeacher({...teacher,subject:e.target.value})}/><input placeholder="Qualification" value={teacher.qualification} onChange={e=>setTeacher({...teacher,qualification:e.target.value})}/><input placeholder="Photo URL" value={teacher.image_url} onChange={e=>setTeacher({...teacher,image_url:e.target.value})}/></div><button className="saveBtn" onClick={saveTeacher}>{editingTeacher?'Update Faculty':'Add Faculty'}</button></div><div className="teacherAdminGrid">{teachers.map(t=><div className="teacherAdmin" key={t.id}><img src={t.image_url||'/placeholder.svg'} alt={t.name}/><div><b>{t.name}</b><span>{t.subject}</span><small>{t.qualification}</small></div><button onClick={()=>{setEditingTeacher(t.id);setTeacher({name:t.name||'',subject:t.subject||'',qualification:t.qualification||'',image_url:t.image_url||''})}}>Edit</button><button className="danger" onClick={()=>remove('teachers',t.id)}>Delete</button></div>)}</div></div>}
 {tab==='gallery'&&<div><div className="panel formPanel"><h3>Add a school photo</h3><div className="formGrid"><input placeholder="Photo title" value={photo.title} onChange={e=>setPhoto({...photo,title:e.target.value})}/><input placeholder="Image URL" value={photo.image_url} onChange={e=>setPhoto({...photo,image_url:e.target.value})}/></div>{photo.image_url&&<img className="uploadPreview" src={photo.image_url} alt="Preview"/>}<button className="saveBtn" onClick={savePhoto}>Add to Gallery</button></div><div className="galleryAdminGrid">{gallery.map(g=><div className="galleryAdmin" key={g.id}><img src={g.image_url} alt={g.title}/><div><b>{g.title||'School photo'}</b><button className="danger" onClick={()=>remove('gallery',g.id)}>Delete</button></div></div>)}</div></div>}
 {tab==='admissions'&&<div className="panel"><div className="panelHead"><h3>Admission enquiries</h3><span>{admissions.length} total</span></div>{admissions.map(a=><div className="admissionRow" key={a.id}><div><b>{a.student_name}</b><span>Class {a.class_applied} • Father: {a.father_name}</span><small>{a.phone} • {a.address}</small></div><button className="danger" onClick={()=>remove('admissions',a.id)}>Delete</button></div>)}{!admissions.length&&<p className="empty">No admission enquiries yet.</p>}</div>}
 </section></div>
}
