'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { supabase } from '../lib/supabase'

const fallback = {
  school_name: 'New Sunrise Public School', tagline: 'Learn • Lead • Shine',
  hero_title: 'Where curiosity becomes confidence.',
  hero_subtitle: 'A joyful, disciplined and future-ready learning environment for Nursery to Class 8 in Kallyangaon.',
  hero_image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=2200&q=88', logo_url: '',
  about_image: 'https://images.unsplash.com/photo-1497486751825-1233686d5d80?auto=format&fit=crop&w=1400&q=88',
  principal_image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=88'
}
const Arrow = () => <span aria-hidden="true">↗</span>
export default function Home() {
  const [settings,setSettings]=useState<Record<string,string>>(fallback),[notices,setNotices]=useState<any[]>([]),[teachers,setTeachers]=useState<any[]>([]),[gallery,setGallery]=useState<any[]>([]),[loading,setLoading]=useState(true)
  useEffect(()=>{async function load(){const [s,n,t,g]=await Promise.all([supabase.from('site_settings').select('key,value'),supabase.from('notices').select('*').order('published_on',{ascending:false}).limit(4),supabase.from('teachers').select('*').order('id').limit(6),supabase.from('gallery').select('*').order('id',{ascending:false}).limit(8)]);const mapped={...fallback} as Record<string,string>;(s.data||[]).forEach((x:any)=>{mapped[x.key]=x.value});setSettings(mapped);setNotices(n.data||[]);setTeachers(t.data||[]);setGallery(g.data||[]);setLoading(false)}load()},[])
  useEffect(()=>{const items=document.querySelectorAll<HTMLElement>('.premiumSection,.metricStrip,.campusBand,.galleryPremium,.admissionPremium');items.forEach(i=>i.classList.add('motionReady'));const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('motionVisible');o.unobserve(e.target)}}),{threshold:.12});items.forEach(i=>o.observe(i));return()=>o.disconnect()},[])
  return <main className="site-premium">
    <div className="announcement"><div><span className="liveDot"/> Admissions open for 2026–27 · Nursery to Class 8</div><div className="announcementRight"><span>📍 Kallyangaon, Bihar</span><span>☎ {settings.phone||'+91 XXXXX XXXXX'}</span></div></div>
    <header className="premiumNav"><a href="#home" className="premiumBrand"><div className="premiumLogo">{settings.logo_url?<img src={settings.logo_url} alt="School logo"/>:'NS'}</div><div><strong>{settings.school_name}</strong><small>{settings.tagline}</small></div></a><nav className="premiumLinks"><a href="#home">Home</a><a href="#about">About</a><a href="#academics">Academics</a><a href="#faculty">Faculty</a><a href="#campus">Campus</a><a href="#notices">Updates</a></nav><div className="premiumActions"><Link href="/student" className="studentButton">Student Login</Link><Link href="/admission" className="admissionButton">Admissions <Arrow/></Link></div></header>
    <section id="home" className="premiumHero">
      <div className="heroImage" style={{backgroundImage:`url(${settings.hero_image})`}}/><div className="heroOverlay"/><div className="heroGlow heroGlowOne"/><div className="heroGlow heroGlowTwo"/>
      <div className="heroInner"><div className="heroCopy"><div className="heroKicker"><span>NEW SUNRISE</span> · ESTABLISHING A BRIGHTER TOMORROW</div><h1>{settings.hero_title}</h1><p>{settings.hero_subtitle}</p><div className="heroButtons"><Link href="/admission" className="heroPrimary">Begin Admission <Arrow/></Link><a href="#about" className="heroGhost">Discover our school <Arrow/></a></div><div className="heroTrust"><span>✓ Nursery–Class 8</span><span>✓ Child-centred learning</span><span>✓ Safe & caring environment</span></div></div></div>
      <div className="heroTextPanel"><div><span>NEW SUNRISE</span><strong>Learn. Lead. Shine.</strong></div></div><a className="scrollCue" href="#about">Scroll to explore <span>↓</span></a>
    </section>
    <section className="metricStrip"><div><strong>Nursery–8</strong><span>Classes offered</span></div><div><strong>2026–27</strong><span>Admissions open</span></div><div><strong>01 Sep</strong><span>School opening</span></div><div><strong>Kallyangaon</strong><span>Bihar · 854317</span></div></section>
    <section id="about" className="premiumSection aboutPremium"><div className="sectionVisual"><div className="visualAccent"/><img src={settings.about_image} alt="Students learning at school"/><div className="visualBadge"><strong>01</strong><span>Our<br/>approach</span></div></div><div className="sectionCopy"><div className="sectionEyebrow">ABOUT NEW SUNRISE</div><h2>Education with purpose, warmth and ambition.</h2><p className="lead">We believe a great school does more than teach lessons. It helps children ask better questions, discover their strengths and grow into responsible, confident people.</p><p>New Sunrise Public School brings together a strong academic foundation, values, creativity and practical learning in a caring environment designed for every stage from Nursery to Class 8.</p><div className="valueRows"><div><b>01</b><span>Strong foundations</span><small>Concept-first learning that lasts.</small></div><div><b>02</b><span>Whole-child growth</span><small>Academics, arts, sports and character.</small></div><div><b>03</b><span>Personal attention</span><small>Every child seen, supported and encouraged.</small></div></div><a href="#academics" className="underLink">Explore our learning approach <Arrow/></a></div></section>
    <section id="academics" className="premiumSection academicsPremium"><div className="sectionHeading"><div><div className="sectionEyebrow">ACADEMICS</div><h2>A thoughtful journey through every stage.</h2></div><p>Age-appropriate teaching, active learning and regular assessment help children build knowledge with confidence.</p></div><div className="academicGrid">{[['01','Early Years','Nursery · LKG · UKG','Play, language, numbers, movement and discovery.'],['02','Primary','Classes I–V','Strong literacy, numeracy, science and social understanding.'],['03','Middle School','Classes VI–VIII','Concepts, problem-solving, communication and independent thinking.']].map(x=><article key={x[0]}><span className="cardNumber">{x[0]}</span><div className="cardRule"/><h3>{x[1]}</h3><p>{x[2]}</p><span>{x[3]}</span><a href="#admissions">Learn more <Arrow/></a></article>)}</div></section>
    <section id="campus" className="campusBand"><div className="campusIntro"><div className="sectionEyebrow lightEyebrow">THE NEW SUNRISE EXPERIENCE</div><h2>More than a classroom.</h2><p>A school day shaped by curiosity, creativity, movement, friendship and responsibility.</p></div><div className="campusFeatures">{[['01','Focused academics','Clear concepts and confident learning.'],['02','Creative expression','Arts, activities and imagination.'],['03','Sports & wellness','Healthy habits and team spirit.'],['04','Values & leadership','Respect, discipline and responsibility.']].map(x=><div key={x[0]}><b>{x[0]}</b><strong>{x[1]}</strong><span>{x[2]}</span></div>)}</div></section>
    <section id="faculty" className="premiumSection facultyPremium"><div className="sectionHeading"><div><div className="sectionEyebrow">OUR FACULTY</div><h2>People who make learning matter.</h2></div><p>Dedicated educators who guide students with care, consistency and high expectations.</p></div><div className="facultyGrid">{teachers.map((t,i)=><article className="facultyCard" key={t.id}><div className="facultyPhoto"><img src={t.image_url||'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?auto=format&fit=crop&w=700&q=85'} alt={t.name}/><span>0{i+1}</span></div><div><h3>{t.name}</h3><p>{t.subject}</p><small>{t.qualification}</small></div></article>)}{!teachers.length&&!loading&&<div className="emptyPremium">Faculty profiles will appear here.</div>}</div></section>
    <section id="notices" className="premiumSection updatesPremium"><div className="sectionHeading"><div><div className="sectionEyebrow">FROM THE SCHOOL</div><h2>Latest updates.</h2></div><Link href="/notices" className="underLink">View all updates <Arrow/></Link></div><div className="updatesGrid">{notices.map(n=><article className="updateCard" key={n.id}>{n.image_url&&<img src={n.image_url} alt=""/>}<div className="updateMeta"><span>{new Date(n.published_on).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}</span>{n.important&&<b>IMPORTANT</b>}</div><h3>{n.title}</h3><p>{n.body}</p><a href="/notices">Read update <Arrow/></a></article>)}{!notices.length&&!loading&&<div className="emptyPremium">New school updates will appear here.</div>}</div></section>
    <section className="galleryPremium"><div className="galleryHeading"><div><div className="sectionEyebrow lightEyebrow">SCHOOL LIFE</div><h2>Moments that stay with us.</h2></div><Link href="/gallery" className="lightLink">View gallery <Arrow/></Link></div><div className="premiumGalleryGrid">{gallery.length?gallery.map(g=><img key={g.id} src={g.image_url} alt={g.title}/>):<><img src="https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1000&q=88" alt="School life"/><img src="https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1000&q=88" alt="Students learning"/><img src="https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=1000&q=88" alt="School campus"/></>}</div></section>
    <section id="admissions" className="admissionPremium"><div><div className="sectionEyebrow">ADMISSIONS 2026–27</div><h2>A bright beginning starts here.</h2><p>Applications are open for Nursery to Class 8. Take the first step towards a joyful, purposeful education.</p></div><Link href="/admission" className="heroPrimary">Start Application <Arrow/></Link></section>
    <footer className="premiumFooter"><div className="footerTop"><div className="footerIdentity"><div className="premiumLogo">{settings.logo_url?<img src={settings.logo_url} alt="School logo"/>:'NS'}</div><div><strong>{settings.school_name}</strong><small>{settings.tagline}</small></div><p>Quality education, strong values and a brighter future for every child.</p></div><div><h4>Explore</h4><a href="#about">About</a><a href="#academics">Academics</a><a href="#faculty">Faculty</a><Link href="/gallery">Gallery</Link><Link href="/notices">Updates</Link></div><div><h4>Admissions</h4><Link href="/admission">Apply for 2026–27</Link><Link href="/student">Student Login</Link><a href="#notices">School Updates</a></div><div><h4>Visit us</h4><p>{settings.address||'Kallyangaon, Bihar – 854317'}</p><p>{settings.phone||'+91 XXXXX XXXXX'}</p><p>{settings.email||'info@newsunrisepublicschool.in'}</p></div></div><div className="footerBottom"><span>© {new Date().getFullYear()} {settings.school_name}. All rights reserved.</span><span>Learn · Lead · Shine</span></div></footer>
  </main>
}