'use client'
import {useEffect,useState} from 'react'

const FUNCTION_URL='https://stypnhzdnsgmyngqkpmz.supabase.co/functions/v1/owner-control'

type State={is_active:boolean,updated_at:string|null}

export default function OwnerControl(){
 const [code,setCode]=useState(''),[state,setState]=useState<State|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[unlocked,setUnlocked]=useState(false)
 async function call(action:string,is_active?:boolean,providedCode=code){
  setBusy(true);setError('')
  try{const r=await fetch(FUNCTION_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:providedCode,action,is_active})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');setState({is_active:d.is_active,updated_at:d.updated_at});return d}catch(e){setError(e instanceof Error?e.message:'Something went wrong');throw e}finally{setBusy(false)}
 }
 async function unlock(e:any){e.preventDefault();try{await call('status',undefined,code);setUnlocked(true)}catch{setUnlocked(false)}}
 useEffect(()=>{if(unlocked)call('status').catch(()=>{})},[unlocked])
 if(!unlocked)return <main style={styles.bg}><section style={styles.card}><div style={styles.icon}>🔐</div><h1 style={styles.h1}>Owner Control</h1><p style={styles.muted}>Private website management access</p><form onSubmit={unlock}><input autoFocus type="password" value={code} onChange={e=>setCode(e.target.value)} placeholder="Enter owner code" autoComplete="off" style={styles.input}/><button disabled={busy||!code} style={styles.primary}>{busy?'Checking…':'Unlock Control'}</button></form>{error&&<p style={styles.error}>{error}</p>}</section></main>
 return <main style={styles.bg}><section style={styles.card}><div style={styles.top}><div><div style={styles.label}>OWNER CONTROL</div><h1 style={styles.h1}>Website Status</h1><p style={styles.muted}>Only the owner can change this setting.</p></div><button onClick={()=>{setUnlocked(false);setCode('')}} style={styles.lock}>Lock</button></div><div style={{...styles.status,borderColor:state?.is_active?'#86efac':'#fca5a5'}}><span style={{fontSize:34}}>{state?.is_active?'🟢':'🔴'}</span><div><b style={{fontSize:22}}>{state?.is_active?'WEBSITE ACTIVE':'WEBSITE INACTIVE'}</b><p style={styles.muted}>{state?.is_active?'Public website is available normally.':'Public website pages are temporarily blocked.'}</p></div></div><div style={styles.actions}><button disabled={busy||state?.is_active} onClick={()=>call('set',true)} style={styles.activeBtn}>{busy?'Working…':'✓ Activate Website'}</button><button disabled={busy||state?.is_active===false} onClick={()=>{if(confirm('Deactivate the public website? Student/admin data will not be deleted.'))call('set',false)}} style={styles.offBtn}>{busy?'Working…':'⏸ Deactivate Website'}</button></div><div style={styles.note}><b>Safe shutdown:</b> Deactivation only blocks the public website. Admissions, student profiles, fees, attendance and results remain stored.</div>{state?.updated_at&&<small style={styles.muted}>Last changed: {new Date(state.updated_at).toLocaleString('en-IN')}</small>}</section></main>
}
const styles:any={bg:{minHeight:'100vh',display:'grid',placeItems:'center',padding:24,background:'linear-gradient(135deg,#07111f,#12304a)',fontFamily:'Arial,sans-serif'},card:{width:'min(680px,100%)',padding:36,borderRadius:24,background:'#fff',boxShadow:'0 28px 90px rgba(0,0,0,.35)'},icon:{fontSize:44},h1:{margin:'8px 0',fontSize:32,color:'#102033'},muted:{color:'#64748b',lineHeight:1.6},label:{fontSize:12,fontWeight:800,letterSpacing:2,color:'#64748b'},top:{display:'flex',justifyContent:'space-between',gap:20,alignItems:'start'},lock:{border:'1px solid #cbd5e1',background:'#fff',borderRadius:10,padding:'9px 14px',cursor:'pointer'},input:{width:'100%',boxSizing:'border-box',margin:'22px 0 12px',padding:15,border:'1px solid #cbd5e1',borderRadius:12,fontSize:16},primary:{width:'100%',padding:14,border:0,borderRadius:12,background:'#102a43',color:'#fff',fontWeight:700,cursor:'pointer'},status:{marginTop:28,padding:22,border:'2px solid',borderRadius:18,display:'flex',gap:16,alignItems:'center'},actions:{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,marginTop:18},activeBtn:{padding:15,border:0,borderRadius:12,background:'#166534',color:'#fff',fontWeight:700,cursor:'pointer'},offBtn:{padding:15,border:0,borderRadius:12,background:'#b91c1c',color:'#fff',fontWeight:700,cursor:'pointer'},note:{margin:'18px 0',padding:15,borderRadius:12,background:'#f1f5f9',color:'#334155',lineHeight:1.6},error:{color:'#b91c1c',fontWeight:600}}
