'use client'
import {useEffect,useState} from 'react'

const FUNCTION_URL='https://stypnhzdnsgmyngqkpmz.supabase.co/functions/v1/owner-control'
type Feature={feature_key:string,feature_name:string,description:string|null,enabled:boolean,updated_at:string|null}
type State={is_active:boolean,active_until:string|null,updated_at:string|null,features:Feature[]}

export default function OwnerControl(){
 const [code,setCode]=useState(''),[state,setState]=useState<State|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[unlocked,setUnlocked]=useState(false),[activeUntil,setActiveUntil]=useState(''),[featureBusy,setFeatureBusy]=useState('')
 async function call(action:string,is_active?:boolean,providedCode=code,until=activeUntil){
  setBusy(true);setError('')
  try{const r=await fetch(FUNCTION_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:providedCode,action,is_active,active_until:until||null})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');setState({is_active:d.is_active,active_until:d.active_until??null,updated_at:d.updated_at,features:d.features||state?.features||[]});if(d.active_until!==undefined)setActiveUntil(d.active_until||'');return d}catch(e){setError(e instanceof Error?e.message:'Something went wrong');throw e}finally{setBusy(false)}
 }
 async function setFeature(feature_key:string,enabled:boolean){setFeatureBusy(true);setError('');try{const r=await fetch(FUNCTION_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,action:'set_feature',feature_key,enabled})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to update feature');await call('status',undefined,code)}catch(e){setError(e instanceof Error?e.message:'Unable to update feature')}finally{setFeatureBusy(false)}}
 async function unlock(e:any){e.preventDefault();try{await call('status',undefined,code);setUnlocked(true)}catch{setUnlocked(false)}}
 useEffect(()=>{if(unlocked)call('status').catch(()=>{})},[unlocked])
 if(!unlocked)return <main style={styles.bg}><section style={styles.card}><div style={styles.icon}>🔐</div><h1 style={styles.h1}>Owner Control</h1><p style={styles.muted}>Private website management access</p><form onSubmit={unlock}><input autoFocus type="password" value={code} onChange={e=>setCode(e.target.value)} placeholder="Enter owner code" autoComplete="off" style={styles.input}/><button disabled={busy||!code} style={styles.primary}>{busy?'Checking…':'Unlock Control'}</button></form>{error&&<p style={styles.error}>{error}</p>}</section></main>
 return <main style={styles.bg}><section style={styles.card}><div style={styles.top}><div><div style={styles.label}>OWNER CONTROL</div><h1 style={styles.h1}>Website Status</h1><p style={styles.muted}>Control manual status or set an automatic expiry date.</p></div><button onClick={()=>{setUnlocked(false);setCode('')}} style={styles.lock}>Lock</button></div><div style={{...styles.status,borderColor:state?.is_active?'#86efac':'#fca5a5'}}><span style={{fontSize:34}}>{state?.is_active?'🟢':'🔴'}</span><div><b style={{fontSize:22}}>{state?.is_active?'WEBSITE ACTIVE':'WEBSITE INACTIVE'}</b><p style={styles.muted}>{state?.is_active?'Public website is available normally.':'Public website pages are temporarily blocked.'}</p>{state?.is_active&&state.active_until&&<p style={styles.expiry}>Active until: <b>{new Date(state.active_until+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'2-digit',year:'numeric'})}</b></p>}</div></div><div style={styles.schedule}><div><b>Active Upto</b><p style={styles.muted}>Website will stay active through this date. After this date, it will automatically become inactive.</p></div><input type="date" value={activeUntil} onChange={e=>setActiveUntil(e.target.value)} min={new Date().toISOString().slice(0,10)} style={styles.date}/></div><div style={styles.actions}><button disabled={busy} onClick={()=>call('set',true)} style={styles.activeBtn}>{busy?'Working…':state?.is_active?'✓ Update Active Upto':'✓ Activate Website'}</button><button disabled={busy||state?.is_active===false} onClick={()=>{if(confirm('Deactivate the public website? Student/admin data will not be deleted.'))call('set',false)}} style={styles.offBtn}>{busy?'Working…':'⏸ Deactivate Website'}</button></div><div style={styles.note}><b>Automatic expiry:</b> If an Active Upto date is selected, the website stays active through that date. Starting the next date, the public website and admin panel automatically become inactive. Data is never deleted.</div><div style={styles.featureBox}><div><div style={styles.label}>FEATURE MANAGEMENT</div><h2 style={{margin:'6px 0',color:'#102033'}}>School Management Features</h2><p style={styles.muted}>Turn individual modules ON or OFF. OFF modules are hidden from the admin dashboard and blocked from their management pages.</p></div><div style={styles.featureGrid}>{(state?.features||[]).map(f=><div key={f.feature_key} style={styles.featureRow}><div><b>{f.feature_name}</b><small style={styles.featureDesc}>{f.description||''}</small></div><button disabled={featureBusy} onClick={()=>setFeature(f.feature_key,!f.enabled)} style={{...styles.toggle,background:f.enabled?'#166534':'#64748b'}}>{f.enabled?'ON':'OFF'}</button></div>)}</div><p style={styles.featureNote}>Feature settings do not delete student data or records. They only control availability.</p></div>{state?.updated_at&&<small style={styles.muted}>Last changed: {new Date(state.updated_at).toLocaleString('en-IN')}</small>}</section></main>
}
const styles:any={bg:{minHeight:'100vh',display:'grid',placeItems:'center',padding:24,background:'linear-gradient(135deg,#07111f,#12304a)',fontFamily:'Arial,sans-serif'},card:{width:'min(680px,100%)',padding:36,borderRadius:24,background:'#fff',boxShadow:'0 28px 90px rgba(0,0,0,.35)'},icon:{fontSize:44},h1:{margin:'8px 0',fontSize:32,color:'#102033'},muted:{color:'#64748b',lineHeight:1.6},label:{fontSize:12,fontWeight:800,letterSpacing:2,color:'#64748b'},top:{display:'flex',justifyContent:'space-between',gap:20,alignItems:'start'},lock:{border:'1px solid #cbd5e1',background:'#fff',borderRadius:10,padding:'9px 14px',cursor:'pointer'},input:{width:'100%',boxSizing:'border-box',margin:'22px 0 12px',padding:15,border:'1px solid #cbd5e1',borderRadius:12,fontSize:16},primary:{width:'100%',padding:14,border:0,borderRadius:12,background:'#102a43',color:'#fff',fontWeight:700,cursor:'pointer'},status:{marginTop:28,padding:22,border:'2px solid',borderRadius:18,display:'flex',gap:16,alignItems:'center'},expiry:{margin:'6px 0 0',color:'#166534'},schedule:{marginTop:18,padding:18,border:'1px solid #e2e8f0',borderRadius:16,display:'flex',justifyContent:'space-between',gap:18,alignItems:'center',background:'#f8fafc'},date:{padding:12,border:'1px solid #cbd5e1',borderRadius:10,fontSize:16},actions:{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,marginTop:18},activeBtn:{padding:15,border:0,borderRadius:12,background:'#166534',color:'#fff',fontWeight:700,cursor:'pointer'},offBtn:{padding:15,border:0,borderRadius:12,background:'#b91c1c',color:'#fff',fontWeight:700,cursor:'pointer'},note:{margin:'18px 0',padding:15,borderRadius:12,background:'#f1f5f9',color:'#334155',lineHeight:1.6},featureNote:{margin:'12px 0 0',color:'#475569',fontSize:13},featureDesc:{display:'block',marginTop:4,color:'#64748b',lineHeight:1.4},featureBox:{marginTop:24,padding:20,border:'1px solid #e2e8f0',borderRadius:18,background:'#f8fafc'},featureGrid:{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginTop:16},featureRow:{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,padding:13,border:'1px solid #e2e8f0',borderRadius:12,background:'#fff'},toggle:{minWidth:62,padding:'9px 12px',border:0,borderRadius:999,color:'#fff',fontWeight:800,cursor:'pointer'},error:{color:'#b91c1c',fontWeight:600}}
