'use client'
import {useEffect,useState} from 'react'
import {useRouter} from 'next/navigation'
import Link from 'next/link'
import {supabase} from '../../../lib/supabase'
import '../admin.css'

export default function AdmissionsManagement(){
 const router=useRouter();const[rows,setRows]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[msg,setMsg]=useState('');const[busy,setBusy]=useState<number|null>(null)
 async function load(){const{data:s}=await supabase.auth.getSession();if(!s.session){router.replace('/admin');return}const{data,error}=await supabase.from('admissions').select('*').eq('status','pending').order('id',{ascending:false});if(error)setMsg(error.message);else setRows(data||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 async function approve(a:any){if(!confirm(`Approve admission for ${a.student_name}?`))return;setBusy(a.id);const{error:e}=await supabase.from('admissions').update({status:'verified',reviewed_at:new Date().toISOString()}).eq('id',a.id);if(e){setMsg(e.message);setBusy(null);return}const{error:p}=await supabase.from('student_profiles').upsert({admission_id:a.id,student_id:a.student_unique_id,student_name:a.student_name,dob:a.dob,class_name:a.class_applied,father_name:a.father_name,mother_name:a.mother_name,phone:a.phone,email:a.email,address:a.address,student_photo_url:a.student_photo_url,status:'active',updated_at:new Date().toISOString()},{onConflict:'admission_id'});if(p){await supabase.from('admissions').update({status:'pending',reviewed_at:null}).eq('id',a.id);setMsg(p.message);setBusy(null);return}setRows(v=>v.filter(x=>x.id!==a.id));setMsg('Admission approved — student moved to Approved Students ✓');setBusy(null)}
 async function reject(a:any){if(!confirm(`Reject and permanently remove ${a.student_name}'s application? The admission form will need to be filled again.`))return;setBusy(a.id);const{error}=await supabase.from('admissions').delete().eq('id',a.id);if(error)setMsg(error.message);else{setRows(v=>v.filter(x=>x.id!==a.id));setMsg('Application rejected and removed. The student must submit a new admission form.')}setBusy(null)}
 const fmt=(v:any)=>v?new Date(String(v).includes('T')?v:`${v}T00:00:00`).toLocaleDateString('en-IN'):'—'
 return <main className="studentsPage"><header className="studentsPageHead"><div><span className="adminKicker">ADMISSION MANAGEMENT</span><h1>Pending Admissions</h1><p>Only website applications waiting for approval are shown here.</p></div><Link href="/admin" className="backDashboard">← Back to Dashboard</Link></header><div className="studentListBar"><div><strong>{rows.length}</strong><span>Pending Applications</span></div><div className="studentListNote">Approved applications automatically move to Approved Students.</div></div>{msg&&<div className="toast">{msg}</div>}{loading?<div className="studentEmpty">Loading applications…</div>:!rows.length?<div className="studentEmpty"><strong>No pending admissions</strong><span>New website admission forms will appear here.</span></div>:<div className="approvedStudentsGrid">{rows.map(a=><article key={a.id} className="approvedStudentCard" style={{cursor:'default'}}><div className="approvedStudentPhoto">{a.student_photo_url?<img src={a.student_photo_url} alt=""/>:<span>{(a.student_name||'S').slice(0,1).toUpperCase()}</span>}</div><div className="approvedStudentInfo"><span className="studentStatus">PENDING VERIFICATION</span><h2>{a.student_name}</h2><strong>{a.application_number||'Application'}</strong><p>Class {a.class_applied||'—'} · DOB {fmt(a.dob)}</p><small>Father: {a.father_name||'—'} · Mobile: {a.phone||'—'}</small></div><div style={{display:'flex',gap:8,flexWrap:'wrap',alignItems:'center',justifyContent:'flex-end'}}><button className="viewBtn" disabled={busy===a.id} onClick={()=>approve(a)}>✓ Approve</button><button className="viewBtn" style={{background:'#fff0f0',color:'#b42318',border:'1px solid #f0b8b8'}} disabled={busy===a.id} onClick={()=>reject(a)}>✕ Reject & Remove</button></div></article>)}</div>}</main>
}
