'use client'

import {useEffect,useState} from 'react'
import Link from 'next/link'
import {supabase} from '../../../lib/supabase'
import '../admin.css'
import '../dashboard-cards.css'
import './enquiries.css'

type Enquiry={id:number;name:string;phone:string;email:string|null;subject:string|null;message:string;status:string;admin_response:string|null;responded_at:string|null;created_at:string}

export default function AdminEnquiries(){
 const [session,setSession]=useState<any>(null),[allowed,setAllowed]=useState<boolean|null>(null),[items,setItems]=useState<Enquiry[]>([]),[selected,setSelected]=useState<Enquiry|null>(null),[response,setResponse]=useState(''),[status,setStatus]=useState('new'),[filter,setFilter]=useState('all'),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();setSession(session);if(!session){setAllowed(false);return}const {data}=await supabase.from('admin_users').select('user_id').eq('user_id',session.user.id).maybeSingle();setAllowed(!!data)})()},[])
 async function load(){setBusy(true);const {data,error}=await supabase.from('enquiries').select('*').order('created_at',{ascending:false});if(error)setMsg(error.message);else setItems(data||[]);setBusy(false)}
 useEffect(()=>{if(allowed)load()},[allowed])
 async function save(){if(!selected)return;setBusy(true);const {error}=await supabase.from('enquiries').update({admin_response:response.trim()||null,status,responded_at:response.trim()?new Date().toISOString():null}).eq('id',selected.id);setMsg(error?error.message:'Enquiry updated ✓');if(!error){setSelected(null);await load()}setBusy(false)}
 function replyUrl(type:'email'|'whatsapp',e:Enquiry){const text=`Hello ${e.name},\n\n${response.trim()||'Regarding your enquiry to New Sunrise Public School.'}\n\nRegards,\nNew Sunrise Public School`;if(type==='email')return e.email?`mailto:${e.email}?subject=${encodeURIComponent('Reply from New Sunrise Public School')}&body=${encodeURIComponent(text)}`:'';const digits=e.phone.replace(/\D/g,'');return digits?`https://wa.me/${digits}?text=${encodeURIComponent(text)}`:''}
 function openReply(type:'email'|'whatsapp'){if(!selected)return;const url=replyUrl(type,selected);if(!url){setMsg(type==='email'?'This enquiry has no email address.':'This enquiry has no valid phone number.');return}window.open(url,'_blank','noopener,noreferrer')}
 const filtered=filter==='all'?items:items.filter(x=>x.status===filter)
 if(allowed===null)return <div className="adminEnquiryLoading">Checking admin access…</div>
 if(!session||!allowed)return <div className="adminLogin"><div className="loginCard"><div className="brandmark">NS</div><span className="adminKicker">NEW SUNRISE PUBLIC SCHOOL</span><h1>Admin access required</h1><p>Please sign in through the main admin portal to manage enquiries.</p><Link href="/admin">Go to Admin Portal →</Link></div></div>
 return <div className="adminShell enquiryAdminShell"><aside><div className="adminBrand"><div className="brandmark">NS</div><div><b>New Sunrise</b><small>School Admin</small></div></div><div className="sideLabel">MANAGE</div><Link className="adminSideLink" href="/admin">⌂ Dashboard</Link><Link className="adminSideLink active" href="/admin/enquiries">✉ Enquiries</Link><div className="sideBottom"><Link href="/">↗ View live website</Link><button onClick={()=>supabase.auth.signOut()}>⇥ Logout</button></div></aside><section className="adminMain"><header className="adminTop"><div><small>COMMUNICATION MANAGEMENT</small><h1>Enquiries</h1></div><div className="topActions"><Link className="backDashboard" href="/admin">← Back to Dashboard</Link>{busy&&<span>Saving…</span>}<span className="adminUser">● {session.user?.email}</span></div></header>{msg&&<div className="toast">{msg}</div>}
 <div className="welcome enquiryWelcome"><div><span className="adminKicker">ENQUIRY DESK</span><h2>Questions from parents & visitors.</h2><p>Read every enquiry, write the official response, then open the visitor’s email or WhatsApp with the message ready to send.</p></div><div className="enquiryStats"><strong>{items.filter(x=>x.status==='new').length}</strong><span>New enquiries</span></div></div>
 <div className="enquiryFilters"><div>{['all','new','in_progress','answered','closed'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x==='all'?'All':x.replace('_',' ')}</button>)}</div><span>{filtered.length} enquiries</span></div>
 <div className="enquiryAdminGrid"><div className="panel enquiryListPanel">{filtered.map(e=><button className={`enquiryRow ${e.status}`} key={e.id} onClick={()=>{setSelected(e);setResponse(e.admin_response||'');setStatus(e.status)}}><div className="enquiryAvatar">{e.name.slice(0,1).toUpperCase()}</div><div className="enquiryRowMain"><div><strong>{e.name}</strong><span className={`statusBadge ${e.status}`}>{e.status.replace('_',' ')}</span></div><b>{e.subject||'General enquiry'}</b><p>{e.message}</p><small>{new Date(e.created_at).toLocaleString('en-IN')}</small></div><span className="chevron">›</span></button>)}{!filtered.length&&<div className="emptyState"><strong>No enquiries here</strong><span>New enquiries submitted on the website will appear in this panel.</span></div>}</div>
 <div className="panel enquiryReplyPanel">{selected?<><div className="replyHeader"><div><span className="adminKicker">ENQUIRY #{selected.id}</span><h3>{selected.name}</h3><p>{selected.phone}{selected.email?` · ${selected.email}`:''}</p></div><span className={`statusBadge ${selected.status}`}>{selected.status.replace('_',' ')}</span></div><div className="messageBox"><span>{selected.subject||'General enquiry'}</span><p>{selected.message}</p></div><label className="responseLabel">ADMIN RESPONSE<textarea value={response} onChange={e=>setResponse(e.target.value)} placeholder="Write the response you want to send…"/></label><div className="responseActions"><button onClick={()=>openReply('whatsapp')} className="whatsappBtn">WhatsApp ↗</button><button onClick={()=>openReply('email')} className="emailBtn">Email ↗</button></div><div className="replySaveRow"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="new">New</option><option value="in_progress">In progress</option><option value="answered">Answered</option><option value="closed">Closed</option></select><button className="saveBtn" onClick={save} disabled={busy}>Save Response</button></div>{selected.responded_at&&<small className="respondedAt">Last responded {new Date(selected.responded_at).toLocaleString('en-IN')}</small>}</>:<div className="emptyReply"><div>✉</div><h3>Select an enquiry</h3><p>Choose a message from the left to read it and prepare a response.</p></div>}</div></div>
 </section></div>
}